name: myfirstapp
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  step_progress_indicator: ^1.0.2
  percent_indicator: ^4.2.3
  shared_preferences: ^2.2.1



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_nav_bar: ^5.0.6
  smooth_page_indicator: ^1.1.0
  google_fonts: ^5.1.0
  group_list_view: ^1.1.1
  flutter_group_list_view: ^1.0.3 
dev_dependencies:
  flutter_test:
    sdk: flutter





  flutter_lints: ^2.0.0


flutter:
  assets:
      - assets/img/
    
  